from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')
old="""  function localPoint(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}\n  function applyPointer(side,p){const horizontal=(side==='left')!==swapped;if(horizontal)leftP.targetX=p.x;else rightP.targetY=p.y}\n  if('PointerEvent'in window){\n    canvas.addEventListener('pointerdown',e=>{e.preventDefault();const p=localPoint(e),side=p.x<split?'left':'right';activePointers.set(e.pointerId,side);try{canvas.setPointerCapture(e.pointerId)}catch{}applyPointer(side,p);if(state==='running'||state==='countdown')ensureAudio()},{passive:false});\n    canvas.addEventListener('pointermove',e=>{const side=activePointers.get(e.pointerId);if(!side)return;e.preventDefault();applyPointer(side,localPoint(e))},{passive:false});\n    const release=e=>activePointers.delete(e.pointerId);canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',release);\n  }else{\n    canvas.addEventListener('touchstart',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();for(const t of e.changedTouches){const p={x:t.clientX-r.left,y:t.clientY-r.top},side=p.x<split?'left':'right';activePointers.set(t.identifier,side);applyPointer(side,p)}if(state==='running'||state==='countdown')ensureAudio()},{passive:false});\n    canvas.addEventListener('touchmove',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();for(const t of e.changedTouches){const side=activePointers.get(t.identifier);if(side)applyPointer(side,{x:t.clientX-r.left,y:t.clientY-r.top})}},{passive:false});\n    const release=e=>{for(const t of e.changedTouches)activePointers.delete(t.identifier)};canvas.addEventListener('touchend',release);canvas.addEventListener('touchcancel',release);\n  }\n"""
new="""  function localPoint(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}\n  const sideOwners={left:null,right:null};\n  function clearPointers(){activePointers.clear();sideOwners.left=null;sideOwners.right=null}\n  function claimPointer(id,side){if(sideOwners[side]!==null)return false;sideOwners[side]=id;activePointers.set(id,side);return true}\n  function releasePointer(id){const side=activePointers.get(id);if(!side)return;activePointers.delete(id);if(sideOwners[side]===id)sideOwners[side]=null}\n  function applyPointer(side,p){\n    const horizontal=(side==='left')!==swapped;\n    if(horizontal){const minX=side==='left'?0:split,maxX=side==='left'?split:W;leftP.targetX=clamp(p.x,minX,maxX)}else rightP.targetY=p.y;\n  }\n  if('PointerEvent'in window){\n    canvas.addEventListener('pointerdown',e=>{e.preventDefault();const p=localPoint(e),side=p.x<split?'left':'right';if(!claimPointer(e.pointerId,side))return;try{canvas.setPointerCapture(e.pointerId)}catch{}applyPointer(side,p);if(state==='running'||state==='countdown')ensureAudio()},{passive:false});\n    canvas.addEventListener('pointermove',e=>{const side=activePointers.get(e.pointerId);if(!side)return;e.preventDefault();applyPointer(side,localPoint(e))},{passive:false});\n    const release=e=>releasePointer(e.pointerId);canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',release);\n  }else{\n    canvas.addEventListener('touchstart',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();for(const t of e.changedTouches){const p={x:t.clientX-r.left,y:t.clientY-r.top},side=p.x<split?'left':'right';if(claimPointer(t.identifier,side))applyPointer(side,p)}if(state==='running'||state==='countdown')ensureAudio()},{passive:false});\n    canvas.addEventListener('touchmove',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();for(const t of e.changedTouches){const side=activePointers.get(t.identifier);if(side)applyPointer(side,{x:t.clientX-r.left,y:t.clientY-r.top})}},{passive:false});\n    const release=e=>{for(const t of e.changedTouches)releasePointer(t.identifier)};canvas.addEventListener('touchend',release);canvas.addEventListener('touchcancel',release);\n  }\n"""
if old not in s:
    raise SystemExit('touch block not found')
s=s.replace(old,new,1)
# Replace gameplay-level clears so ownership cannot survive pause/reset/game over.
s=s.replace("activePointers.clear();lastTime=performance.now();", "clearPointers();lastTime=performance.now();")
s=s.replace("state='paused';activePointers.clear();releaseWakeLock();", "state='paused';clearPointers();releaseWakeLock();")
s=s.replace("state='over';activePointers.clear();releaseWakeLock();", "state='over';clearPointers();releaseWakeLock();")
s=s.replace("countdownToken++;activePointers.clear();releaseWakeLock();", "countdownToken++;clearPointers();releaseWakeLock();")
# Add touch diagnostics to the health surface.
needle="nearMisses,swapped,recentBalance:recentBalance()"
if needle not in s:
    raise SystemExit('health needle not found')
s=s.replace(needle,"nearMisses,swapped,activePointers:activePointers.size,leftPointerOwned:sideOwners.left!==null,rightPointerOwned:sideOwners.right!==null,recentBalance:recentBalance()",1)
p.write_text(s,encoding='utf-8')
